{% set name = "perl-devel-nytprof" %}
{% set version = "6.14" %}
{% set sha256 = "ac24dd7da5b2247696becefc15ca935484367743aad44cb2c8cfa17a29ad8e03" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/J/JK/JKEENAN/Devel-NYTProf-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 1
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl
    - perl-capture-tiny
    - perl-file-which
    - perl-json-maybexs
    - perl-test-differences
    - perl-text-diff
  run:
    - perl
    - perl-file-which   # does not define run export
    - perl-text-diff    # does not define run export

test:
  imports:
    - Devel::NYTProf
    - Devel::NYTProf::Core
  commands:
    # Version outdated or undef:
    - perl -we 'use Devel::NYTProf::Constants'
    - perl -we 'use Devel::NYTProf::Data'
    - perl -we 'use Devel::NYTProf::FileHandle'
    - perl -we 'use Devel::NYTProf::FileInfo'
    - perl -we 'use Devel::NYTProf::ReadStream'
    - perl -we 'use Devel::NYTProf::Reader'
    - perl -we 'use Devel::NYTProf::Run'
    - perl -we 'use Devel::NYTProf::SubCallInfo'
    - perl -we 'use Devel::NYTProf::SubInfo'
    - perl -we 'use Devel::NYTProf::Util'
    # Binaries:
    - nytprofcalls --help >/dev/null
    - nytprofcsv --help >/dev/null
    - nytprofhtml --help >/dev/null
    - nytprofmerge --help >/dev/null

about:
  home: https://code.google.com/archive/p/perl-devel-nytprof
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  summary: Powerful fast feature-rich Perl source code profiler

extra:
  recipe-maintainers:
    - xileF1337
    - cbrueffer
